ath11k_nss: replace rcu_read_unlock with spin_unlock
Mistakenly edited the patch by hand thinking I had incorrectly imported
it from @BS.

Original patch was throwing
```
peer.c:572:1: error: label at end of compound statement is a C23 extension
```

Moved spin_unlocks into exit as that's what it would have been doing
anyways.

Signed-off-by: Sean Khan <datapronix@protonmail.com>
(cherry picked from commit 7a93211a700d249afc29f7fc96b9f0be426fee67)